<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>225deebe-45dc-4c15-9613-552fe162dcfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root-webapp-purdygo']/main/div/nav/div[2]/div[2]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;profile-placeholder&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d89494de-ed7d-46a6-b221-693690f9acdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/dirpbkmoz/image/upload/w_300,h_300,c_thumb,r_max,g_face,z_0.7,f_auto,q_auto:good/v1698271445/purdygo/user/5f107d4806f9730011b2e506/profile/yhj1dx6u0oiqtmpwcz1e</value>
      <webElementGuid>24dbb60c-a64e-4b07-8f5e-8359fe0f66fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>profile-placeholder</value>
      <webElementGuid>954f2354-25e7-4d91-ae3b-bfd8ea171dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-webapp-purdygo&quot;)/main[1]/div[@class=&quot;sc-oUAMm kkeujj&quot;]/nav[@class=&quot;sc-pcwJP fvyGwI&quot;]/div[@class=&quot;sc-psrQp devxIj&quot;]/div[@class=&quot;sc-plgA-D dNfjzh&quot;]/div[@class=&quot;sc-pIgJL iEEddX&quot;]/a[1]/div[@class=&quot;sc-ptBBy eMfoGb&quot;]/img[1]</value>
      <webElementGuid>3a18190e-7d27-48fb-b772-5cdf6d5a02e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root-webapp-purdygo']/main/div/nav/div[2]/div[2]/div/a/div/img</value>
      <webElementGuid>12d684c4-6af6-4164-92d3-bd64d4aabeb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='profile-placeholder']</value>
      <webElementGuid>7c17177e-161f-45f8-80f4-2093bfb7edb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div/img</value>
      <webElementGuid>60370218-a203-4842-9a27-9f0175197e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/dirpbkmoz/image/upload/w_300,h_300,c_thumb,r_max,g_face,z_0.7,f_auto,q_auto:good/v1698271445/purdygo/user/5f107d4806f9730011b2e506/profile/yhj1dx6u0oiqtmpwcz1e' and @alt = 'profile-placeholder']</value>
      <webElementGuid>4aa488e1-4dea-4023-ad6a-098272e3f323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
