<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>eb30eea2-bdfe-49d7-8e27-f60564a76fef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33248d26-a688-4492-97a0-54fa3f89f2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>78b10fb0-7623-45e8-878e-a626ac61e0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5c20b5bb-a655-42d0-9959-f8c5d3bb13c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>b1bdbcb1-495f-424c-8382-ef84f7e075cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fznKkj kydRoC</value>
      <webElementGuid>b260b448-baf3-4a57-a8b3-c50f31b8eb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defaultLayout&quot;)/div[@class=&quot;sc-qOvHb dutuIt&quot;]/div[@class=&quot;sc-qWQHW hWGjXV&quot;]/div[@class=&quot;sc-oTaid zqGnO&quot;]/form[@class=&quot;sc-paWVw jeEIBW&quot;]/div[@class=&quot;sc-fznyAO gWMoJH&quot;]/input[@class=&quot;sc-fznKkj kydRoC&quot;]</value>
      <webElementGuid>fb2a9bc3-1900-42ae-adae-7fb18d19d9bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Password']</value>
      <webElementGuid>a11b66f6-c8c3-44ce-8982-c247723df2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='defaultLayout']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>42226bed-1b83-4151-88b7-fa689b901410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6aa948e5-39d1-40a7-a309-5a2ed6d6db4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Password' and @type = 'password' and @placeholder = 'Contraseña']</value>
      <webElementGuid>33476a11-791f-4613-8a4c-81209c2cd2cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
