<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dni</name>
   <tag></tag>
   <elementGuidId>c4f93357-4681-41ca-bbbc-ce537453cd13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dni']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dni&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>985f0467-5478-4700-ac9c-010f90dff1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dni</value>
      <webElementGuid>c5af7db0-6e86-487d-8435-66c8c773bd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>791f5e78-7b24-43d8-8279-d2b6f760f982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cédula</value>
      <webElementGuid>cbac3d48-dbb5-4cdf-9811-ead69b3589c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fznKkj kydRoC</value>
      <webElementGuid>c04e7c6d-b194-4671-9236-ed89163957be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defaultLayout&quot;)/div[@class=&quot;sc-qOvHb dutuIt&quot;]/div[@class=&quot;sc-qWQHW hWGjXV&quot;]/div[@class=&quot;sc-oTaid zqGnO&quot;]/form[@class=&quot;sc-paWVw jeEIBW&quot;]/div[@class=&quot;sc-fznyAO gWMoJH&quot;]/input[@class=&quot;sc-fznKkj kydRoC&quot;]</value>
      <webElementGuid>c180c552-f6f2-44d8-810f-2a2cebadbfdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dni']</value>
      <webElementGuid>bf34f887-9ae4-4a6a-99b0-924881416e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='defaultLayout']/div/div/div[2]/form/div/input</value>
      <webElementGuid>22cdea30-9332-4810-a440-539e3f33a4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dae39c06-58ae-4ed9-bb05-494538ff2ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dni' and @type = 'text' and @placeholder = 'Cédula']</value>
      <webElementGuid>7b9ed8c8-91b2-4fbe-9de7-dedec533d73f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
